# Generated by Django 3.1.3 on 2021-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210405_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=20, null=True),
        ),
    ]
